name: ifa_21312103
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  get: 4.6.6
  google_sign_in: ^6.1.5
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/facebook.png
    - assets/uti.png
